### PR TITLE
clean up somewhat and use new MOI.Test tests

### PR DESCRIPTION
**Pull request by chriscoey**
@blegat @odow what is the simplest way to select the right set of MOI.Test functions to include/exclude? With the first commit here, there are dozens of MOI test functions that fail - too many to list by hand. Many fail because Pavito errors on instances without integer/discrete constraints, but I don't know a simple way to exclude all instances without such constraints.

### CODE REVIEW

**Comment by odow** [comment]
> Many fail because Pavito errors on instances without integer/discrete constraints

We don't have a way of doing this because it's a pretty uncommon ask. You'd have to manually exclude them. you can also partially match function names. So you could have `exclude = ["test_nonlinear_"]` to exclude all nonlinear-related tests.

**Comment by chriscoey** [comment]
Thanks. Given how many need to be excluded, could it make more sense to just list the ones to include? I assume that is what the "include = ..." is for.
Alternatively, I could make pavito not error when there are no discrete constraints, and just call the continuous solver. Not sure what makes the most sense.

**Comment by odow** [comment]
> could it make more sense to just list the ones to include

Yes, that's what `include` is for.

> I could make pavito not error when there are no discrete constraints, and just call the continuous solver.

This seems like the way to go.

**Comment by chriscoey** [comment]
Ok I'll try that. And should I do the module wrapping of MOI tests that I think I've seen in some other packages recently? Or is that not really important?

**Comment by odow** [comment]
It's not necessary, but putting thing in a module gets rid of a bunch of scoping and global variable issues (it's too common for tests to accidentally rely on data/variables set in other parts (or files) or the tests).

**Review by odow — COMMENTED** [review]
I haven't had a look through, but you may as well merge if the tests are passing. I'll take a better look this week once I've made the changes the MOI.

**Pull request merged**
